{
 "title": "DashBoard - Bank API Tweet",
 "description": "Metrics about Grafana",
 "tags": [
  "grafana",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Active instances",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{job=\"my-application-bank-tweet-api\"}"
    }
   ]
  },
  {
   "title": "Quantidade de Execução",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "node_request_operations_total" }
   ]
  },
  {
   "title": "Quantidade Erros API",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(node_request_duration_seconds_count{code=\"500\"}) by(method, code)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "content": "<br />\n<br />\n<center>\n<img src=\"public/img/grafana_icon.svg\"  style=\"height: 60px;\">\n<span style=\"color: red;font-size:3rem;line-height: 2rem;\">💖</span>\n<img src=\"public/app/plugins/datasource/prometheus/img/prometheus_logo.svg\" alt=\"Prometheus logo\" style=\"height: 60px;\">\n</center>"
  },
  {
   "title": "http status codes com sucesso e erro",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "Quantidade" }
   ],
   "targets": [
    {
     "expr": "sum(node_request_duration_seconds_count{code != \" \", method = \"GET\" }) by( code)"
    }
   ]
  },
  {
   "title": "Latência - Tempo de Execução",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_request_duration_seconds_count{route=\"/information/lang\"}[1m])) by (route, method)  * 60",
     "legendFormat": "País/Regiao"
    },
    {
     "expr": "sum(irate(node_request_duration_seconds_count{route=\"/information/topuser\"}[1m])) by (route, method)  * 60",
     "legendFormat": "Topuser"
    },
    {
     "expr": "sum(irate(node_request_duration_seconds_count{route=\"/information/dia\"}[1m])) by (route, method)  * 60",
     "legendFormat": "TweetDia"
    }
   ]
  },
  {
   "title": "Consumo Memoria Aplicação",
   "type": "graph",
   "description": "Aggregated over all Grafana nodes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"my-application-bank-tweet-api\"})",
     "legendFormat": "memory usage"
    }
   ]
  }
 ]
}